### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by jiri132** [jiri132/Flare#1]
## Why themes?
> Themes make it easy for everyone to customize their own experience in the application

## Description of task
There should be a base interface for everything that you have to fill in so an `interface` that should always be the `extends` type named `Theme`, Every other theme component should start with `export interface {Theme_name} extends Theme = {}` and then you can begin to create your own theme.

## Tasks
- [x] base interface called `Theme`
- [x] standard `dark` theme
- [x] `Standard Object Styling` type
- [x] components get added to the base interface `Theme` with `SOSt` 
- [x] Primary, Secondary color templates

**Comment by N3v1** [comment]
Hi @jiri132,
I have an idea for a color theme: Shades-Of-Purple

**Comment by jiri132** [comment]
Ooh I will open a new issue where people could suggest themes! I think that would make a fun thing!

This was more of a production thingy to keep track of what had to be done for custom themes. :)
